<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>openxmlsdk_native</AssemblyName>

    <!-- 默认版本号为 3.5.1，支持命令行通过 -p:OpenXmlPackageVersion=xxx 动态覆盖 -->
    <OpenXmlPackageVersion Condition="'$(OpenXmlPackageVersion)' == ''">3.5.1</OpenXmlPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="$(OpenXmlPackageVersion)" />
  </ItemGroup>
</Project>
