<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <NativeLib>Static</NativeLib>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>openxmlsdk_native_ios</AssemblyName>

    <OpenXmlPackageVersion Condition="'$(OpenXmlPackageVersion)' == ''">3.5.1</OpenXmlPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="$(OpenXmlPackageVersion)" />
  </ItemGroup>
</Project>
